### ISSUE TITLE
2nd resubmission todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/phenology_estimators#14]
- [x] Put A - I labels on all plots
- [x] knock down the DPI so they're < 3000 pixels across
- [x] reference new A-I labels in text

**Comment by sdtaylor** [comment]
accepted :1st_place_medal:
