### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/phenology_estimators#3]
- [x] finalize abstract
- [x] normalize which side the errors are on for all figs
- [x] figure showing how many estimates were dropped
- [x] software citation paragraph
- [x] end estimates First Observed -> Last Observed
- [x] deal with wiggly peak error density
- [x] underestimate/overestimate arrows
- [x] figure "Percent Yes" -> "Presence Percent"
- [x] figure "Weibull Curve" -> "Weibull"
- [x] put figures in
- [x] run thru grammar checker
- [x] make markdown/pdf version
- [x] make zenodo repo
- [x] italicise spp names
- [x] R2 -> R^2
- [x] order sample size in figures
- [x] supp figures
- [x] remove titles from figures

preprint version
- [ ] 10pt font
- [ ] single space
- [ ] no line numbers
- [ ] sup figures at end

**Comment by sdtaylor** [comment]
keywords

onset, peak, flowering, budburst, sampling frequency, herbarium records

**Comment by sdtaylor** [comment]
Acknowledgements:

I thank A. Waananen and the team of the Echinacea Project for providing the phenology data set. 

-any proof readers

Funding
This research was supported by the Gordon and Betty Moore Foundation’s Data-Driven Discovery Initiative through Grant GBMF4563 to Ethan P. White.

**Comment by sdtaylor** [comment]
Accepted :100:
